name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build app
        run: |
          go mod tidy
          scripts/buildprod.sh

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: "latest"

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Check if the SQLite database exists
        run: |
          DB_PATH=$(echo $DATABASE_URL | sed 's/sqlite3:\/\///')
          DB_DIR=$(dirname $DB_PATH)

          # Проверяем, существует ли директория
          if [ ! -d "$DB_DIR" ]; then
            echo "Directory $DB_DIR does not exist. Creating it now..."
            mkdir -p "$DB_DIR"
          fi

          # Проверяем, существует ли файл базы данных
          if [ -f "$DB_PATH" ]; then
            echo "Database file found."
          else
            echo "Database file NOT found. Creating it now..."
            touch "$DB_PATH"
          fi

      - name: Run database migrations
        run: goose -dir ./sql/schema sqlite3 $DATABASE_URL up

      - name: "Deploy to Cloud Run"
        run: |
          gcloud info
          gcloud builds submit --tag us-central1-docker.pkg.dev/notely-453609/notely-ar-repo/notely-app:latest .
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-453609/notely-ar-repo/notely-app:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely
          
      # - name: Build app

      #   run: ./scripts/buildprod.sh
        
      # - name: Run database migrations
      #   run: goose -dir ./sql/schema sqlite3 $DATABASE_URL up

      # - name: Google Auth
      #   id: auth
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: notely-453609

      # - name: Build and push Docker image to Google Artifact Registry
      #   run: |
      #     gcloud builds submit --tag us-central1-docker.pkg.dev/notely-453609/notely-ar-repo/notely:latest .
          
      # - name: Deploy to Cloud Run
      #   run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-453609/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-453609 --max-instances=4
      